# Generated by Django 5.2 on 2025-05-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[], db_index=True, default='NEW_AVAILABLE', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.bank')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(choices=[('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Processing at Top Bank)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')], max_length=255)),
                ('status_to', models.CharField(choices=[('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Processing at Top Bank)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')], max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason_for_change', models.TextField(blank=True, help_text="e.g., 'Software upgrade v2.1 required', 'Screen malfunction reported by Ecom Bank Branch X'", null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Device History',
                'ordering': ['-changed_at'],
            },
        ),
    ]
