# Generated by Django 5.2 on 2025-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
