# Generated by Django 5.2 on 2025-07-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='about',
            field=models.CharField(blank=True, help_text='You can state the location of that particular branch. \nExample: Kumasi, Accra, etc.', max_length=255, null=True),
        ),
    ]
