# Generated by Django 5.2 on 2025-05-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_bank_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
    ]
