# Generated by Django 5.2 on 2025-05-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_bank_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Processing at Top Bank)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')], default=(('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Processing at Top Bank)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')), max_length=255),
        ),
    ]
