# Generated by Django 5.2 on 2025-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_resolve_duplicate_serials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Porcessing)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')], default=(('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Porcessing)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')), max_length=255),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='status_from',
            field=models.CharField(choices=[('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Porcessing)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='status_to',
            field=models.CharField(choices=[('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Porcessing)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')], max_length=255),
        ),
    ]
