# Generated by Django 5.2 on 2025-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_options_device_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('NEW_AVAILABLE', 'New - Available for Assignment'), ('ASSIGNED', 'Assigned to Bank'), ('RETURNED_FAULTY', 'Returned - Faulty'), ('RETURNED_UPGRADE', 'Returned - Needs Upgrade'), ('IN_CUSTODY', 'In Custody (Porcessing)'), ('DISPATCHED', 'Dispatched (Sent back to Bank)')], default='NEW_AVAILABLE', max_length=255),
        ),
    ]
