# Generated by Django 5.0.4 on 2024-05-16 10:00 # Adjust date if necessary, but not critical

from django.db import migrations

def resolve_duplicates(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    # Identified duplicate: serial_number '1017521' for IDs 1 and 4
    # We will modify the one with the higher ID (4)
    try:
        device_to_update = Device.objects.get(id=4, serial_number='1017521')
        device_to_update.serial_number = '1017521_DUP1' # Make it unique
        device_to_update.save(update_fields=['serial_number'])
    except Device.DoesNotExist:
        # In case it was already fixed or the state is not as expected,
        # we can skip. This makes the migration more robust.
        pass

def unresolve_duplicates(apps, schema_editor):
    # This function is for reversing the migration.
    # We attempt to revert the serial number if it matches the modified one.
    Device = apps.get_model('devices', 'Device')
    try:
        device_to_revert = Device.objects.get(id=4, serial_number='1017521_DUP1')
        device_to_revert.serial_number = '1017521'
        device_to_revert.save(update_fields=['serial_number'])
    except Device.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_status'), # Depends on the migration before 0005
    ]

    operations = [
        migrations.RunPython(resolve_duplicates, reverse_code=unresolve_duplicates),
    ]
